name: flutter_redemption_scbtechx
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.0.2
  logger: ^1.3.0
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  dropdown_button2: ^2.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  loading_animation_widget: ^1.2.0+4
  decimal: ^2.3.2
  string_validator: ^1.0.0
  intl: ^0.18.0
  loader_overlay: ^2.1.0
  cool_alert: ^2.0.1
  bloc_test: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
